#!/bin/bash

mysql -e "STOP REPLICA;
CHANGE REPLICATION SOURCE TO SOURCE_HOST='192.168.0.221', SOURCE_USER='repl', SOURCE_PASSWORD='Slave#2023', SOURCE_AUTO_POSITION = 1, GET_SOURCE_PUBLIC_KEY = 1;
START REPLICA;"
