network:
    version: 2
    renderer: networkd
    ethernets:
      enp0s8:
        dhcp4: no
        addresses: [192.168.0.223/24]
        routes:
          - to: default
            via: 192.168.0.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 8.8.4.4
